ALTER TABLE tamers DELETE CONSTRAINT unique_user_original_url IF EXISTS;
ALTER TABLE tamers DELETE CONSTRAINT fk_user IF EXISTS;
ALTER TABLE tamers DELETE COLUMN user_id IF EXISTS;
DROP TABLE IF EXISTS users;