ALTER TABLE tamers DROP CONSTRAINT IF EXISTS unique_user_original_url;
-- ALTER TABLE tamers DROP FOREIGN KEY IF EXISTS fk_user;
ALTER TABLE tamers DROP COLUMN IF EXISTS user_id;
DROP TABLE IF EXISTS users CASCADE;